### ISSUE TITLE
Auto typegen doesn't work out of the box

### ISSUE THREAD

**Issue by shmuli9** [jacobparis/underkill-stack#7]
For automatic RR7 typegen through the typescript plugin, would be handy to add the '.vscode/settings.json' with the correct values. This might not be the most "underkill", so at least a mention in the readme to do this manually in the IDE would be appreciated

Happy to open a PR if this would be helpful?

**Comment by jacobparis** [comment]
You're right this should be included – you're welcome to make a PR, otherwise I'll get to it soon

**Comment by shmuli9** [comment]
I created this PR #8

**Comment by jacobparis** [comment]
Fixed in #8
